name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Create local changes
        run: |
          now=$(date +"%D %T")
          echo "[$now] Yes, it is." >> status_log.txt
      - name: Auto green
        run: |
          git config --local user.email "2071916845@qq.com"
          git config --local user.name "it985"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 30
          keep_minimum_runs: 6
